/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Tue Mar 03 16:30:57 PST 2015
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.codehaus.jackson.annotate.JsonProperty;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;

/**
 * Salesforce DTO for SObject EntitySubscription
 */
@XStreamAlias("EntitySubscription")
public class EntitySubscription extends AbstractSObjectBase {

    // ParentId
    private String ParentId;

    @JsonProperty("ParentId")
    public String getParentId() {
        return this.ParentId;
    }

    @JsonProperty("ParentId")
    public void setParentId(String ParentId) {
        this.ParentId = ParentId;
    }

    // SubscriberId
    private String SubscriberId;

    @JsonProperty("SubscriberId")
    public String getSubscriberId() {
        return this.SubscriberId;
    }

    @JsonProperty("SubscriberId")
    public void setSubscriberId(String SubscriberId) {
        this.SubscriberId = SubscriberId;
    }

}