/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Tue Mar 03 16:30:57 PST 2015
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.codehaus.jackson.annotate.JsonProperty;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;

/**
 * Salesforce DTO for SObject OpportunityCompetitor
 */
@XStreamAlias("OpportunityCompetitor")
public class OpportunityCompetitor extends AbstractSObjectBase {

    // OpportunityId
    private String OpportunityId;

    @JsonProperty("OpportunityId")
    public String getOpportunityId() {
        return this.OpportunityId;
    }

    @JsonProperty("OpportunityId")
    public void setOpportunityId(String OpportunityId) {
        this.OpportunityId = OpportunityId;
    }

    // CompetitorName
    private String CompetitorName;

    @JsonProperty("CompetitorName")
    public String getCompetitorName() {
        return this.CompetitorName;
    }

    @JsonProperty("CompetitorName")
    public void setCompetitorName(String CompetitorName) {
        this.CompetitorName = CompetitorName;
    }

    // Strengths
    private String Strengths;

    @JsonProperty("Strengths")
    public String getStrengths() {
        return this.Strengths;
    }

    @JsonProperty("Strengths")
    public void setStrengths(String Strengths) {
        this.Strengths = Strengths;
    }

    // Weaknesses
    private String Weaknesses;

    @JsonProperty("Weaknesses")
    public String getWeaknesses() {
        return this.Weaknesses;
    }

    @JsonProperty("Weaknesses")
    public void setWeaknesses(String Weaknesses) {
        this.Weaknesses = Weaknesses;
    }

}