/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Tue Mar 03 16:30:57 PST 2015
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.codehaus.jackson.annotate.JsonProperty;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;

/**
 * Salesforce DTO for SObject UserLicense
 */
@XStreamAlias("UserLicense")
public class UserLicense extends AbstractSObjectBase {

    // LicenseDefinitionKey
    private String LicenseDefinitionKey;

    @JsonProperty("LicenseDefinitionKey")
    public String getLicenseDefinitionKey() {
        return this.LicenseDefinitionKey;
    }

    @JsonProperty("LicenseDefinitionKey")
    public void setLicenseDefinitionKey(String LicenseDefinitionKey) {
        this.LicenseDefinitionKey = LicenseDefinitionKey;
    }

    // MonthlyLoginsUsed
    private Integer MonthlyLoginsUsed;

    @JsonProperty("MonthlyLoginsUsed")
    public Integer getMonthlyLoginsUsed() {
        return this.MonthlyLoginsUsed;
    }

    @JsonProperty("MonthlyLoginsUsed")
    public void setMonthlyLoginsUsed(Integer MonthlyLoginsUsed) {
        this.MonthlyLoginsUsed = MonthlyLoginsUsed;
    }

    // MonthlyLoginsEntitlement
    private Integer MonthlyLoginsEntitlement;

    @JsonProperty("MonthlyLoginsEntitlement")
    public Integer getMonthlyLoginsEntitlement() {
        return this.MonthlyLoginsEntitlement;
    }

    @JsonProperty("MonthlyLoginsEntitlement")
    public void setMonthlyLoginsEntitlement(Integer MonthlyLoginsEntitlement) {
        this.MonthlyLoginsEntitlement = MonthlyLoginsEntitlement;
    }

}